/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#fffbff",
        "outline": "#7b7487",
        "secondary": "#4648d4",
        "inverse-on-surface": "#eef0ff",
        "secondary-container": "#6063ee",
        "on-tertiary-container": "#b7efff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004e5c",
        "tertiary-fixed": "#acedff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#07006c",
        "tertiary": "#005766",
        "on-primary-container": "#ede0ff",
        "on-error-container": "#93000a",
        "on-background": "#131b2e",
        "secondary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#5a00c6",
        "surface-dim": "#d2d9f4",
        "surface-tint": "#732ee4",
        "surface-bright": "#faf8ff",
        "on-surface-variant": "#4a4455",
        "on-primary-fixed": "#25005a",
        "surface-container-low": "#f2f3ff",
        "primary-container": "#7c3aed",
        "on-primary": "#ffffff",
        "background": "#faf8ff",
        "surface": "#faf8ff",
        "surface-container": "#eaedff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#4cd7f6",
        "inverse-surface": "#283044",
        "on-tertiary-fixed": "#001f26",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#d2bbff",
        "outline-variant": "#ccc3d8",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-container-highest": "#dae2fd",
        "tertiary-container": "#007184",
        "secondary-fixed": "#e1e0ff",
        "primary": "#630ed4",
        "surface-container-high": "#e2e7ff",
        "inverse-primary": "#d2bbff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#eaddff",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg":  ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md":  ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm":  ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "code-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["11px", { lineHeight: "16px", fontWeight: "500" }],
      },
      keyframes: {
        ping: {
          "75%, 100%": { transform: "scale(2)", opacity: "0" },
        },
        spin: {
          to: { transform: "rotate(360deg)" },
        },
        bounce: {
          "0%, 100%": { transform: "translateY(-25%)", animationTimingFunction: "cubic-bezier(0.8,0,1,1)" },
          "50%": { transform: "none", animationTimingFunction: "cubic-bezier(0,0,0.2,1)" },
        },
        pulse: {
          "50%": { opacity: ".5" },
        },
      },
    },
  },
  plugins: [],
}
